// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentAnalytics.Context;

#nullable disable

namespace StudentAnalytics.Migrations
{
    [DbContext(typeof(StudentAnalyticsSystemContext))]
    [Migration("20260217235731_AlterStudentTable")]
    partial class AlterStudentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StudentAnalytics.Models.Assignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssignmentType")
                        .HasColumnType("enum('participation','regular','quiz','test')")
                        .HasColumnName("assignment_type");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateTime?>("DateAssigned")
                        .HasColumnType("datetime")
                        .HasColumnName("date_assigned");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime")
                        .HasColumnName("due_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ClassId" }, "class_id");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("StudentAnalytics.Models.Attendance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date")
                        .HasColumnName("attendance_date");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int")
                        .HasColumnName("enrollment_id");

                    b.Property<ushort>("Period")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("period");

                    b.Property<string>("Status")
                        .HasColumnType("enum('present','absent','tardy','excused','half_day')")
                        .HasColumnName("status");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EnrollmentId" }, "enrollment_id");

                    b.HasIndex(new[] { "TeacherId" }, "teacher_id");

                    b.ToTable("attendances", (string)null);
                });

            modelBuilder.Entity("StudentAnalytics.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("class_name");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<ushort>("Period")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("period");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int")
                        .HasColumnName("school_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Subject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('math','science','social_studies','ela','other')")
                        .HasColumnName("subject")
                        .HasDefaultValueSql("'other'");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SchoolId" }, "school_id");

                    b.HasIndex(new[] { "TeacherId" }, "teacher_id")
                        .HasDatabaseName("teacher_id1");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("StudentAnalytics.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "StudentId" }, "student_id");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("StudentAnalytics.Models.Efmigrationshistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("MigrationId")
                        .HasName("PRIMARY");

                    b.ToTable("__efmigrationshistory", (string)null);
                });

            modelBuilder.Entity("StudentAnalytics.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateOnly>("EnrollmentDate")
                        .HasColumnType("date")
                        .HasColumnName("enrollment_date");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("semester");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ClassId" }, "class_id")
                        .HasDatabaseName("class_id1");

                    b.HasIndex(new[] { "StudentId" }, "student_id")
                        .HasDatabaseName("student_id1");

                    b.ToTable("enrollments", (string)null);
                });

            modelBuilder.Entity("StudentAnalytics.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("schools", (string)null);
                });

            modelBuilder.Entity("StudentAnalytics.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('male','female','other')")
                        .HasColumnName("gender")
                        .HasDefaultValueSql("'other'");

                    b.Property<ushort>("GradeLevel")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("grade_level");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("middle_name");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int")
                        .HasColumnName("school_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SchoolId" }, "school_id")
                        .HasDatabaseName("school_id1");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("StudentAnalytics.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("assignment_id");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int")
                        .HasColumnName("enrollment_id");

                    b.Property<ushort?>("Grade")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("grade");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("submitted_date");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AssignmentId" }, "assignment_id");

                    b.HasIndex(new[] { "EnrollmentId" }, "enrollment_id")
                        .HasDatabaseName("enrollment_id1");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("StudentAnalytics.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email_address");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int")
                        .HasColumnName("school_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SchoolId" }, "school_id")
                        .HasDatabaseName("school_id2");

                    b.HasIndex(new[] { "UserId" }, "user_id");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("StudentAnalytics.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int")
                        .HasColumnName("school_id");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('teacher','admin','other')")
                        .HasColumnName("user_type")
                        .HasDefaultValueSql("'other'");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SchoolId" }, "school_id")
                        .HasDatabaseName("school_id3");

                    b.HasIndex(new[] { "Username" }, "username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("StudentAnalytics.Models.Assignment", b =>
                {
                    b.HasOne("StudentAnalytics.Models.Class", "Class")
                        .WithMany("Assignments")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("assignments_ibfk_1");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("StudentAnalytics.Models.Attendance", b =>
                {
                    b.HasOne("StudentAnalytics.Models.Enrollment", "Enrollment")
                        .WithMany("Attendances")
                        .HasForeignKey("EnrollmentId")
                        .IsRequired()
                        .HasConstraintName("attendances_ibfk_1");

                    b.HasOne("StudentAnalytics.Models.Teacher", "Teacher")
                        .WithMany("Attendances")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("attendances_ibfk_2");

                    b.Navigation("Enrollment");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudentAnalytics.Models.Class", b =>
                {
                    b.HasOne("StudentAnalytics.Models.School", "School")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolId")
                        .IsRequired()
                        .HasConstraintName("classes_ibfk_1");

                    b.HasOne("StudentAnalytics.Models.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("classes_ibfk_2");

                    b.Navigation("School");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudentAnalytics.Models.Contact", b =>
                {
                    b.HasOne("StudentAnalytics.Models.Student", "Student")
                        .WithMany("Contacts")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("contacts_ibfk_1");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentAnalytics.Models.Enrollment", b =>
                {
                    b.HasOne("StudentAnalytics.Models.Class", "Class")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("enrollments_ibfk_1");

                    b.HasOne("StudentAnalytics.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("enrollments_ibfk_2");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentAnalytics.Models.Student", b =>
                {
                    b.HasOne("StudentAnalytics.Models.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .IsRequired()
                        .HasConstraintName("students_ibfk_1");

                    b.Navigation("School");
                });

            modelBuilder.Entity("StudentAnalytics.Models.Submission", b =>
                {
                    b.HasOne("StudentAnalytics.Models.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .IsRequired()
                        .HasConstraintName("submissions_ibfk_2");

                    b.HasOne("StudentAnalytics.Models.Enrollment", "Enrollment")
                        .WithMany("Submissions")
                        .HasForeignKey("EnrollmentId")
                        .IsRequired()
                        .HasConstraintName("submissions_ibfk_1");

                    b.Navigation("Assignment");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("StudentAnalytics.Models.Teacher", b =>
                {
                    b.HasOne("StudentAnalytics.Models.School", "School")
                        .WithMany("Teachers")
                        .HasForeignKey("SchoolId")
                        .IsRequired()
                        .HasConstraintName("teachers_ibfk_2");

                    b.HasOne("StudentAnalytics.Models.User", "User")
                        .WithMany("Teachers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("teachers_ibfk_1");

                    b.Navigation("School");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentAnalytics.Models.User", b =>
                {
                    b.HasOne("StudentAnalytics.Models.School", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("users_ibfk_1");

                    b.Navigation("School");
                });

            modelBuilder.Entity("StudentAnalytics.Models.Assignment", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("StudentAnalytics.Models.Class", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("StudentAnalytics.Models.Enrollment", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("StudentAnalytics.Models.School", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Students");

                    b.Navigation("Teachers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("StudentAnalytics.Models.Student", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("StudentAnalytics.Models.Teacher", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Classes");
                });

            modelBuilder.Entity("StudentAnalytics.Models.User", b =>
                {
                    b.Navigation("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
